# This is required so that Netlify doesn't get triggered when unrelated files change.
# Each build uses credits, and triggering builds unnecessarily is wasteful.
name: "Deploy Docs"

on:
  workflow_dispatch: {}

jobs:
  deploy-docs:
    name: "Deploy Docs"
    runs-on: ubuntu-latest
    steps:
    - run: curl -X POST "https://api.netlify.com/build_hooks/${{ secrets.DOCS_NETLIFY_BUILD_HOOK
        }}"
